name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  push-docker:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/3_coursework:latest

  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies 
        run: |
          pip3 install --upgrade pip 
          pip3 install -r requirements.txt
          mkdir output
          python3 build/coursework.py > output/output.txt
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Results_graphs
          path: output
  
  notify:
    runs-on: ubuntu-20.04
      steps:
        - name: send telegram message on push
          uses: appleboy/telegram-action@master
          with:
            to: ${{ secrets.TELEGRAM_TO }}
            token: ${{ secrets.TELEGRAM_FROM }}
            message: |
              ${{ github.actor }} ${{ github.repository }}
              https://github.com/${{ github.repository }}/commit/${{github.sha}}
